### ISSUE TITLE
[Bug] can not deploy mariadb instance when using longhorn

### ISSUE THREAD

**Issue by vnwnv** [mariadb-operator/mariadb-operator#1040]
**Documentation**
- I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

1. Follow the quick start guide, mariadb can not start. the pod is in crashloopbackoff state.
2. Example config need update, `examples/manifests/config/mariadb-secret.yaml` dose not match `examples/manifests/mariadb.yaml`. The secret will not be used.

Add envirement varible `MARIADB_AUTO_UPGRADE` can fix this problem. and the mariadb start normally. but I'm afraid this is not the right way.

**Expected behaviour**

**Steps to reproduce the bug**

Follow the quick start guide

1. `kubectl apply -f examples/manifests/config`
2. `kubectl apply -f examples/manifests/mariadb.yaml`

**Debug information**

here are the logs.

```txt
2024-11-08 12:52:47+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.4.3+maria~ubu2404 started.
2024-11-08 12:52:47+00:00 [Note] [Entrypoint]: MariaDB upgrade information missing, assuming required
2024-11-08 12:52:47+00:00 [Note] [Entrypoint]: MariaDB upgrade (mariadb-upgrade or creating healthcheck users) required, but skipped due to $MARIADB_AUTO_UPGRADE setting
2024-11-08 12:52:47 0 [Note] Starting MariaDB 11.4.3-MariaDB-ubu2404 source revision 5ab81ffe0097a22a774957df28c5223cf0201de3 server_uid /No6dB5uN3IRkjzj//e6OQ603Ik= as process 1
2024-11-08 12:52:47 0 [Note] mariadbd: Aria engine: starting recovery
recovered pages: 0% 37% 100% (0.1 seconds); tables to flush: 1 0 (0.1 seconds); 
2024-11-08 12:52:48 0 [Note] mariadbd: Aria engine: recovery done
2024-11-08 12:52:48 0 [Note] InnoDB: Compressed tables use zlib 1.3
2024-11-08 12:52:48 0 [Note] InnoDB: Number of transaction pools: 1
2024-11-08 12:52:48 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-11-08 12:52:48 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2024-11-08 12:52:48 0 [Note] InnoDB: Using liburing
2024-11-08 12:52:48 0 [Note] InnoDB: Initializing buffer pool, total size = 1.000GiB, chunk size = 16.000MiB
2024-11-08 12:52:48 0 [Note] InnoDB: Completed initialization of buffer pool
2024-11-08 12:52:48 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-11-08 12:52:51 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=18038
2024-11-08 12:52:51 0 [Note] InnoDB: End of log at LSN=37808
2024-11-08 12:52:51 0 [Note] InnoDB: To recover: 146 pages
2024-11-08 12:52:52 0 [Note] InnoDB: Opened 3 undo tablespaces
2024-11-08 12:52:52 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2024-11-08 12:52:52 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2024-11-08 12:52:52 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2024-11-08 12:52:52 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2024-11-08 12:52:52 0 [Note] InnoDB: log sequence number 37808; transaction id 4
2024-11-08 12:52:52 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-11-08 12:52:52 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-11-08 12:52:52 0 [Note] InnoDB: Cannot open '/var/lib/mysql/ib_buffer_pool' for reading: No such file or directory
2024-11-08 12:52:52 0 [Note] Plugin 'wsrep-provider' is disabled.
2024-11-08 12:52:52 0 [Note] Recovering after a crash using tc.log
2024-11-08 12:52:52 0 [Note] Starting table crash recovery...
2024-11-08 12:52:52 0 [Note] Crash table recovery finished.
2024-11-08 12:52:53 0 [Note] DDL_LOG: Crash recovery executed 1 entries
2024-11-08 12:52:56 0 [Note] Server socket created on IP: '0.0.0.0'.
2024-11-08 12:52:56 0 [Note] Server socket created on IP: '::'.
2024-11-08 12:52:56 0 [ERROR] Missing system table mysql.proxies_priv; please run mysql_upgrade to create it
2024-11-08 12:52:56 0 [ERROR] Cannot open mysql.event
2024-11-08 12:52:56 0 [ERROR] mariadbd: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
2024-11-08 12:52:56 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
2024-11-08 12:52:57 0 [Note] mariadbd: ready for connections.
Version: '11.4.3-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-11-08 12:53:07 3 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2024-11-08 12:53:07 4 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2024-11-08 12:53:12 5 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2024-11-08 12:53:12 6 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2024-11-08 12:53:17 7 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2024-11-08 12:53:17 8 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2024-11-08 12:53:17 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2024-11-08 12:53:17 0 [Note] InnoDB: FTS optimize thread exiting.
2024-11-08 12:53:17 0 [Note] InnoDB: Starting shutdown...
2024-11-08 12:53:17 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2024-11-08 12:53:17 0 [Note] InnoDB: Buffer pool(s) dump completed at 241108 12:53:17
2024-11-08 12:53:20 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2024-11-08 12:53:20 0 [Note] InnoDB: Shutdown completed; log sequence number 37840; transaction id 4
2024-11-08 12:53:20 0 [Note] mariadbd: Shutdown complete
```

**Environment details**:
- Kubernetes version: v1.30.6+k3s1
- Kubernetes distribution: k3s
- mariadb-operator version:  0.35.1 and 0.36.0
- Galera data-plane version (init and agent): [Version number]
- Install method: helm

**Additional context**

**Comment by lkvrsfld** [comment]
Hey @vnwnv, 
I a having the same issue. The env variable MARIADB_AUTO_UPGRADE does not seem to fix the issue - after the upgrade process and it's subsequent restart, the issue is back. 

Could it be related to the '[Warning] Access denied for user 'root'@'localhost' (using password: YES)' warning?

**Comment by vnwnv** [comment]
> Hey @vnwnv, I am having the same issue. The env variable MARIADB_AUTO_UPGRADE does not seem to fix the issue - after the upgrade process and it's subsequent restart, the issue is back.
> 
> Could it be related to the '[Warning] Access denied for user 'root'@'localhost' (using password: YES)' warning?

You are right, it is still in crashloopbackoff. I tested the minimal config in 0.35.1, the minimal config can work. But I am not sure which one caused this issue.

**Comment by lkvrsfld** [comment]
I'll try downgrading to 0.35.1. Which example is the minimal config?

**Comment by vnwnv** [comment]
this one in example folder example/manifests/mariadb_minimal.yaml

**Comment by lkvrsfld** [comment]
@vnwnv 
I seem to have found my Issue. by utilizing 
`storage:
    ephemeral: true`
 
The pod Initializes and remains in the running state. 

I am using longhorn on a 3 node cluster... I'll look into the mariadb-operator if there is any reference to such issues

**Comment by lkvrsfld** [comment]
@vnwnv that is also basically the difference between the mariadb_minimal.yaml and the mariadb.yaml manifest. try rolling out using that spec for storage on the other mariadb manifests.

**Comment by vnwnv** [comment]
Same here. 5 node longhorn cluster.

**Comment by vnwnv** [comment]
Tried with `ephemeral: true` the mariadb is working now. but what the reason caused this issue?

**Comment by lkvrsfld** [comment]
@vnwnv The issue seems to be because of the PV / PVC. For testing, I created a StorageClass that allows me to claim volumes with longhorn that do not get replicated => this did not work too. So the issue is basically caused by using storage provided by (in my case) longhorn. 

What CSI / Storage provider are you using?

**Comment by lkvrsfld** [comment]
Here is basically the same issue which got fixed by purging the PVC / Volumes:
https://github.com/bitnami/charts/issues/22214

Assuring it has a new volume / deleting everything is not working for me. When creating a MariaDB resource, and passing in a storage configuration, it fails to log in with root => CrashLoop

**Comment by lkvrsfld** [comment]
@vnwnv Try to delete all existing PVCs related to the MariaDB resource. 

This seemed to fix this for me. (and gave me the ability to use longhorn.)

see https://github.com/bitnami/charts/issues/24727

**Comment by vnwnv** [comment]
It may be something wrong with longhorn. I'm using 5 node longhorn cluster, and use it as default storageclass.
After claim the storageClass to local-path(k3s's default local storage class) the mariadb runs again.

delete PVCs of MariaDB does not fix for me.

**Comment by lkvrsfld** [comment]
I tried using the VolumeClaimTemplate itself in the MariaDBSpec: https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#storage

with the same settings and it somehow worked. 

I am deploying everything using Pulumi dynamically so my manifests aren't YAML, but basically they are the same.

the first time adding the storageclass, size etc. to the VolumeClaimTemplate in "storage:" seemed to fix it for me ( chart v ersion 0.36.0).

then, I deleted all PVCs in the namespace, reverted using the normal values in "storage:" (not using VolumeClaimTemplate) 
as we did before, and mysql worked. very strange.

You can try to use VolumeClaimTemplate, or at least re-assure to delete everything, then check the PVCs, delete it, and also delete the volumes on the longhorn interface. after that, it shouldn't hang on "Access denied for user 'root'@'localhost'".

You could also try to re-create everything from scratch on a new seperate namespace. If it still doesn't work, let's look further into it. would love to get a working / consistent configuration for this operator

**Comment by vnwnv** [comment]
Thanks for your input, I would appreciate it .

i will try these settings.

**Comment by vnwnv** [comment]
still facing this issue, even i reinstalled my cluster. i will continue try to find which one caused this problem.

**Comment by lkvrsfld** [comment]
@vnwnv I can show you my last changes:

Longhorn: 
I created a new StorageClass, which looks like this:

`allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2024-11-09T11:36:44Z"
  name: longhorn-no-replica
  resourceVersion: "2915830"
  uid: 81e1568c-6914-4cef-8604-3107badf1062
parameters:
  fromBackup: ""
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer`

this is my rolled out resource:

`apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  creationTimestamp: "2024-11-09T14:22:09Z"
  generation: 4
  name: mariadb-cluster
  namespace: testing
  resourceVersion: "2966510"
  uid: 25c1a943-0558-4680-b0c4-9ed82d5ee4e8
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mariadb-cluster
        topologyKey: kubernetes.io/hostname
  galera:
    agent:
      gracefulShutdownTimeout: 1s
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:0.36.0
      kubernetesAuth:
        enabled: true
      port: 5555
    availableWhenDonor: false
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
    enabled: true
    galeraLibPath: /usr/lib/galera/libgalera_smm.so
    initContainer:
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:0.36.0
    primary:
      automaticFailover: true
      podIndex: 1
    recovery:
      clusterBootstrapTimeout: 10m0s
      clusterDownscaleTimeout: 5m0s
      clusterHealthyTimeout: 30s
      clusterMonitorInterval: 10s
      clusterUpscaleTimeout: 5m0s
      enabled: true
      minClusterSize: 1
      podRecoveryTimeout: 5m0s
      podSyncTimeout: 5m0s
    replicaThreads: 1
    sst: mariabackup
  image: docker-registry1.mariadb.com/library/mariadb:11.4.3
  metrics:
    enabled: true
    exporter:
      image: prom/mysqld-exporter:v0.15.1
      port: 9104
    passwordSecretKeyRef:
      generate: true
      key: password
      name: mariadb-cluster-metrics-password
    serviceMonitor: {}
    username: mariadb-cluster-metrics
  myCnf: "\n                    [mariadb]\n                    bind-address=*\n                    default_storage_engine=InnoDB\n
    \                   binlog_format=row\n                    innodb_autoinc_lock_mode=2\n
    \                   innodb_buffer_pool_size=1024M\n                    max_allowed_packet=256M\n
    \               "
  myCnfConfigMapKeyRef:
    key: my.cnf
    name: mariadb-cluster-config
  port: 3306
  replicas: 3
  replicasAllowEvenNumber: false
  rootEmptyPassword: false
  rootPasswordSecretKeyRef:
    generate: false
    key: root-password
    name: mariadb-cluster-root-password
  serviceAccountName: mariadb-cluster
  storage:
    ephemeral: false
    resizeInUseVolumes: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: longhorn-no-replica
    waitForVolumeResize: true
  suspend: false
  updateStrategy:
    type: ReplicasFirstPrimaryLast
status:
  conditions:
  - lastTransitionTime: "2024-11-09T14:36:53Z"
    message: Running
    reason: StatefulSetReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-09T14:23:08Z"
    message: Galera initialized
    reason: GaleraInitialized
    status: "True"
    type: GaleraInitialized
  - lastTransitionTime: "2024-11-09T14:36:18Z"
    message: Updated
    reason: Updated
    status: "True"
    type: Updated
  - lastTransitionTime: "2024-11-09T14:27:43Z"
    message: Galera ready
    reason: GaleraReady
    status: "True"
    type: GaleraReady
  - lastTransitionTime: "2024-11-09T14:27:43Z"
    message: Galera configured
    reason: GaleraConfigured
    status: "True"
    type: GaleraConfigured
  currentPrimary: mariadb-cluster-1
  currentPrimaryPodIndex: 1
  replicas: 3`
  
  especially look at the storage config:
  `storage:
    ephemeral: false
    resizeInUseVolumes: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: longhorn-no-replica
    waitForVolumeResize: true`

**Comment by vnwnv** [comment]
still meet this issue.

**Comment by vnwnv** [comment]
Finally I found reason. as I mentioned above the livenessProbe make the probe restarted. :)

After increased initialDelaySeconds in my config, the mariadb initialed and running without errors. The default initialDelaySeconds is only about 20s, which may not enough for embed devices in my situation.

**Comment by VasuInukollu** [comment]
This problem occurs on rook-ceph cluster also. Works fine when not using the storage.

Yaml

```
microk8s kubectl apply -f - <<EOF
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:

  rootEmptyPassword: true

  storage:
    size: 20Gi
    storageClassName: ceph-rbd
  
  image: mariadb:11.4.3
  imagePullPolicy: IfNotPresent

EOF

```

Logs


```
2024-12-20 17:44:01+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.4.3+maria~ubu2404 started.
2024-12-20 17:44:02+00:00 [Note] [Entrypoint]: MariaDB upgrade information missing, assuming required
2024-12-20 17:44:02+00:00 [Note] [Entrypoint]: MariaDB upgrade (mariadb-upgrade or creating healthcheck users) required, but skipped due to $MARIADB_AUTO_UPGRADE setting
2024-12-20 17:44:02 0 [Note] Starting MariaDB 11.4.3-MariaDB-ubu2404 source revision 5ab81ffe0097a22a774957df28c5223cf0201de3 server_uid lLBZfVuHqCmEidI7yVa4GjSoXhk= as process 1
2024-12-20 17:44:02 0 [Note] mariadbd: Aria engine: starting recovery
recovered pages: 0% 30% 99% 100% (0.1 seconds); tables to flush: 2 1 0 (0.1 seconds);
2024-12-20 17:44:02 0 [Note] mariadbd: Aria engine: recovery done
2024-12-20 17:44:02 0 [Note] InnoDB: Compressed tables use zlib 1.3
2024-12-20 17:44:02 0 [Note] InnoDB: Using transactional memory
2024-12-20 17:44:02 0 [Note] InnoDB: Number of transaction pools: 1
2024-12-20 17:44:02 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-12-20 17:44:02 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2024-12-20 17:44:02 0 [Note] InnoDB: Using liburing
2024-12-20 17:44:02 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-12-20 17:44:02 0 [Note] InnoDB: Completed initialization of buffer pool
2024-12-20 17:44:02 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-12-20 17:44:02 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=18006
2024-12-20 17:44:02 0 [Note] InnoDB: End of log at LSN=47086
2024-12-20 17:44:02 0 [Note] InnoDB: To recover: 163 pages
2024-12-20 17:44:02 0 [Note] InnoDB: Opened 3 undo tablespaces
2024-12-20 17:44:02 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2024-12-20 17:44:02 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2024-12-20 17:44:02 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2024-12-20 17:44:02 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2024-12-20 17:44:02 0 [Note] InnoDB: log sequence number 47086; transaction id 14
2024-12-20 17:44:02 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-12-20 17:44:02 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-12-20 17:44:02 0 [Note] InnoDB: Cannot open '/var/lib/mysql/ib_buffer_pool' for reading: No such file or directory
2024-12-20 17:44:02 0 [Note] Plugin 'wsrep-provider' is disabled.
2024-12-20 17:44:02 0 [Note] Recovering after a crash using tc.log
2024-12-20 17:44:02 0 [Note] Starting table crash recovery...
2024-12-20 17:44:02 0 [Note] Crash table recovery finished.
2024-12-20 17:44:03 0 [Note] DDL_LOG: Crash recovery executed 1 entries
2024-12-20 17:44:05 0 [Note] Server socket created on IP: '0.0.0.0'.
2024-12-20 17:44:05 0 [Note] Server socket created on IP: '::'.
2024-12-20 17:44:05 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
2024-12-20 17:44:06 0 [Note] mariadbd: ready for connections.
Version: '11.4.3-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-12-20 17:44:23 3 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2024-12-20 17:44:23 4 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2024-12-20 17:44:28 5 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2024-12-20 17:44:28 6 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2024-12-20 17:44:33 7 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2024-12-20 17:44:33 8 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2024-12-20 17:44:33 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2024-12-20 17:44:33 0 [Note] InnoDB: FTS optimize thread exiting.
2024-12-20 17:44:33 0 [Note] InnoDB: Starting shutdown...
2024-12-20 17:44:33 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2024-12-20 17:44:33 0 [Note] InnoDB: Buffer pool(s) dump completed at 241220 17:44:33
2024-12-20 17:44:36 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2024-12-20 17:44:36 0 [Note] InnoDB: Shutdown completed; log sequence number 47645; transaction id 15
2024-12-20 17:44:36 0 [Note] mariadbd: Shutdown complete

```
